name: Deploy to WP Engine
on:
  push:
    branches:
     - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: |-
          PASTE PRIVATE KEY HERE. FIND IT IN HYPERVAULT, UNDER "Jackrabbit - WP Engine"
        WPE_ENV: your-production-environment-name